# Generated by Django 2.1.1 on 2018-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlbook', '0002_auto_20180925_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
    ]
